### ISSUE TITLE
Reputation tab not showing up in user profile module

### ISSUE THREAD

**Issue by BenSegal855** [power-plugs/PowerRep#2]
As show in the below image, the reputation tab isnt showing up in the user profile module.
![](https://cdn.discordapp.com/attachments/696791268944248924/782044159195742229/unknown.png)

**Comment by CatboyCoding** [comment]
sorry for the super late response and i have no idea why this would be happening, check console (if it's still happening)?

**Comment by BenSegal855** [comment]
It resolved itself a while ago. I should have closed this then but I kinda forgot about it.
